version: '3'
services:
  t3chn0r4d10:
    build: .
    # The code should be copied into the container using COPY.
    # Mount the data folder writable, so that information can be persisted across restarts.
    volumes:
      - ./data/:/data:rw
    ports:
      - "8001:5000"
    expose:
      - 5000
  nginx:
    build: ./nginx
    container_name: techno_radio_nginx
    ports:
      - "5555:5555"
    depends_on:
      - t3chn0r4d10
