version: '3'
services:
  technoradio-checker:
    build: .
    ports:
      - 53037:9060
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=technoradio-mongo
      - MONGO_PORT=27017
      - MONGO_USER=technoradio_checker
      - MONGO_PASSWORD=technoradio_checker
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000

  technoradio-mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: technoradio_checker
      MONGO_INITDB_ROOT_PASSWORD: technoradio_checker
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
